services:
  - type: web
    name: kvasir-dergi
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: HOSTNAME
        value: 0.0.0.0
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
    healthCheckPath: /
    autoDeploy: true
    branch: main
